# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:42
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectID',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='object ID')),
                ('collection_id', models.CharField(max_length=255, verbose_name='collection ID')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
