# Generated by Django 3.0.14 on 2021-07-02 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('registrar', '0002_auto_20160511_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectid',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectids', to='auth.Group'),
        ),
    ]
