# Generated by Django 3.0.14 on 2021-07-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noid',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('naa', models.CharField(max_length=32)),
                ('template', models.CharField(max_length=32)),
                ('n', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
