# Generated by Django 3.0.14 on 2021-07-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noidminter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noid',
            old_name='naa',
            new_name='naan',
        ),
    ]
